-nbad -bap -bfda -nbc -bbo -hnl -br -brf -brs -c33 -cd33 -ncdb -cdw -ce -ci8 -cli0 -d0 -di1 -nfc1 -i8 -ip0 -l0 -nlp -npcs -nprs -npsl -sai -saf -saw -nbs -cs -sc -sob -nfca -cp33 -ss -ts8 -il1 -lc80 -ppi8
-T AavrAsyncCallback
-T AavrInterrupt
-T AavrPoll
-T AavrSemaphore
-T AavrStatus
-T bool
-T FILE
-T GBoxedCopyFunc
-T GDestroyNotify
-T gpointer
-T GSourceFunc
-T size_t
